---
title: "practicaprogramada_3"
author: "Juliana Cruz Gonzáles"
date: "2023-12-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Limpieza de nombres de las columnas
```{r}
library(janitor)
spotify_data <- clean_names(spotify_data)

```

```{r}
library(shiny)
library(shinydashboard)
library(readr)
library(dplyr)
library(ggplot2)



ui <- dashboardPage(
  skin = "yellow",
  dashboardHeader(title = "Top Songs by Spotify"),
  dashboardSidebar(
    selectInput("year", "Year", choices = unique(spotify_data$year)),
    selectInput("genre", "Genre ", choices = unique(spotify_data$`top genre`)),
    selectInput("title", "Song", choices = NULL, multiple = FALSE, selected = NULL),
    downloadButton("downloadBtn", "Download data")
  ),
  dashboardBody(
    tags$style(HTML(".small-box { background-color: yellow; }")), 
    fluidRow(
      valueBoxOutput("bpmBox"),
      valueBoxOutput("energyBox"),
      valueBoxOutput("durationBox")
    ),
    tabsetPanel(
      
      tabPanel("Table",
               dataTableOutput("dataTable")),
      tabPanel("Chart",
               plotOutput("danceabilityPlot"))
    )
  )
)

server <- function(input, output, session) {
  
spotify_data <- read_csv2("/Users/julianacruz/Desktop/shiny_app3/datos/spotify_2000_2023.csv")

 
  title_choices <- reactive({
    filter(spotify_data, 
           year == input$year,
           `top genre` == input$genre) %>%
      pull(title)
  })


  observe({
    updateSelectInput(session, "title", choices = title_choices(), selected = NULL)
  })


  filtered_data <- reactive({
    filter(spotify_data, 
           year == input$year,
           `top genre` == input$genre,
           title %in% input$title)
  })

  
  output$downloadBtn <- downloadHandler(
    filename = function() {
      paste("spotify_data_", input$year, "_", input$genre, ".csv", sep = "")
    },
    content = function(file) {
      write_csv(filtered_data(), file)
    }
  )

 
  output$bpmBox <- renderValueBox({
    selected_song <- filter(filtered_data(), title %in% input$title)
    valueBox(selected_song$bpm, "BPM")
  })

  output$energyBox <- renderValueBox({
    selected_song <- filter(filtered_data(), title %in% input$title)
    valueBox(selected_song$energy, "Energy")
  })

  output$durationBox <- renderValueBox({
    selected_song <- filter(filtered_data(), title %in% input$title)
    valueBox(selected_song$duration, "Duration (min)")
  })


output$danceabilityPlot <- renderPlot({
  ggplot(filtered_data(), aes(x = bpm, y = danceability, color = valence)) +
    geom_point() +
    labs(title = "Gráfico danzabilidad según popularidad") +
    scale_color_gradient(low = "blue", high = "red")  # Personaliza la escala de colores según tus necesidades
})

  # Tabla de datos
  output$dataTable <- renderDataTable({
    filtered_data()
  })
  
 
}

shinyApp(ui, server)

```